### ISSUE TITLE
[Akhaten] Installation impossible

### ISSUE THREAD

**Issue by wouldsmina** [libertempo/web#716]
Après installation, j'obtiens le message : 
````
Notice: Use of undefined constant LOGGER_TOKEN - assumed 'LOGGER_TOKEN' in /var/www/test/includes/define.php on line 62

Notice: Use of undefined constant LOGGER_TOKEN - assumed 'LOGGER_TOKEN' in /var/www/test/includes/define.php on line 72

Fatal error: Uncaught InvalidArgumentException: $config['access_token'] must be 32 characters long, was 'LOGGER_TOKEN' in /var/www/test/vendor/rollbar/rollbar/src/Utilities.php:22 Stack trace: #0 /var/www/test/vendor/rollbar/rollbar/src/Config.php(169): Rollbar\Utilities::validateString('LOGGER_TOKEN', 'config['access_...', 32, false) #1 /var/www/test/vendor/rollbar/rollbar/src/Config.php(139): Rollbar\Config->setAccessToken(Array) #2 /var/www/test/vendor/rollbar/rollbar/src/Config.php(93): Rollbar\Config->updateConfig(Array) #3 /var/www/test/vendor/rollbar/rollbar/src/RollbarLogger.php(21): Rollbar\Config->__construct(Array) #4 /var/www/test/vendor/rollbar/rollbar/src/Rollbar.php(54): Rollbar\RollbarLogger->__construct(Array) #5 /var/www/test/vendor/rollbar/rollbar/src/Rollbar.php(26): Rollbar\Rollbar::setLogger(Array) #6 /var/www/test/includes/define.php(72): Rollbar\Rollbar::init(Array) #7 /var/www/test/index.php(4): require_once('/var/www/test/i...') #8 {main} thrown in /var/www/test/vendor/rollbar/rollbar/src/Utilities.php on line 22
````

Problème non constaté depuis le docker. Après installation (make install) impossible d'accéder à l'authentification. Le vhost me parait correct.

 - Système [i.e. iOS] : DEBIAN
 - Navigateur et version : Firefox 60.2.1esr
 - Erreur dans la console : non

**Serveur (veuillez remplir les informations suivantes):**
 - Système [i.e. iOS8.1] : DEBIAN 9.5
 - Version de Libertempo : Akhaten (develop)
 - Version MySQL et PHP : mariadb  Ver 15.1 Distrib 10.1.26-MariaDB et PHP 7.0.30-0+deb9u1

**Comment by wouldsmina** [comment]
il faut mettre à jour le fichier cfg/env.php
