### ISSUE TITLE
Ajouter un nouvel utilisateur 

### ISSUE THREAD

**Issue by ValentineGI** [libertempo/web#887]
Bonjour,

Voici mon problème lorsque j'essaye d'ajouter un nouvel utilisateur :
`[Thu Feb 06 14:54:11.429315 2020] [php7:error] [pid 20146] [client 192.168.100.78:59970] PHP Fatal error:  Uncaught TypeError: htmlentities() expects parameter 1 to be string, null given in /var/www/gestionconges/hr/hr_ajout_user.php:74\nStack trace:\n#0 /var/www/gestionconges/hr/hr_ajout_user.php(74): htmlentities(NULL, 3)\n#1 /var/www/gestionconges/hr/hr_ajout_user.php(30): dataForm2Array(Array, Object(includes\\SQL), Object(App\\Libraries\\Configuration))\n#2 /var/www/gestionconges/hr/hr_index.php(74): require_once('/var/www/gestio...')\n#3 /var/www/gestionconges/Public/index.php(67): require_once('/var/www/gestio...')\n#4 {main}\n  thrown in /var/www/gestionconges/hr/hr_ajout_user.php on line 74, referer: http://gestionconges.goulard.local/hr/ajout_user`

Merci à vous :+1:

**Comment by wouldsmina** [comment]
Bonjour,
J'ai besoin d'un peu plus d'infos, quelle version de serveur, d'apache, de libertempo... ?
Merci.

**Comment by ValentineGI** [comment]
Ah oui excusé moi :) alors :

- Libertempo 1.13 "Nooma"
- Raspbian GNU Linux 9 
- Debian 9.11
- Server version: Apache/2.4.25 (Raspbian)

Merci à vous, @wouldsmina

**Comment by wouldsmina** [comment]
Merci. Authentification par ldap ? La gestion des heures est elle activé ?

**Comment by ValentineGI** [comment]
Pas d'authentification par LDAP. La gestion des heures sont désactivées

**Comment by wouldsmina** [comment]
C'est un bug lorsque les heures sont désactivées.
J'ai identifié le problème, un patch devrait arriver dans les prochains jours. Merci.
