### ISSUE TITLE
Erreur édition papier

### ISSUE THREAD

**Issue by MaximeVirot** [libertempo/web#903]
Bonjour, 

J'ai un bug quand je vais dans Utilisateur > Édition papier > et je sélectionne Lancer l'édition rien ne s'affiche j'ai une page blanche et si je séléctionne Édition en PDF j'arrive sur une erreur 500. 

J'ai essayer via une autre plateforme et je n'ai pas le problème. J'ai mis à jour mon serveur debian et j'ai vérifier être en derniere version de Libertempo. 

Avez-vous une idée ? 

![screen2](https://user-images.githubusercontent.com/28702604/82219172-31fd3300-991d-11ea-871a-6ca92fa81cfb.png)

**Comment by wouldsmina** [comment]
Bonjour,
Sur quel version de Libertempo ? As tu des messages d'erreurs dans les logs d'apache ?

**Comment by MaximeVirot** [comment]
Bonjour, 

Je suis en version 1.13 et voici le message indiqué dans les log apache : 

[Mon May 25 08:58:40.810849 2020] [php7:error] [pid 28121] [client 77.193.139.138:62226] PHP Fatal error:  Uncaught mysqli_sql_exception: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '' at line 2 in /var/www/Libertempo/adico/includes/SQL.php:151\nStack trace:\n#0 /var/www/Libertempo/adico/includes/SQL.php(151): mysqli->real_query('INSERT INTO con...')\n#1 [internal function]: includes\\Database->query('INSERT INTO con...')\n#2 /var/www/Libertempo/adico/includes/SQL.php(78): call_user_func_array(Array, Array)\n#3 /var/www/Libertempo/adico/edition/Fonctions.php(1180): includes\\SQL::__callStatic('query', Array)\n#4 /var/www/Libertempo/adico/edition/Fonctions.php(1001): edition\\Fonctions::enregistrement_edition('maxime.virot')\n#5 /var/www/Libertempo/adico/edition/edition_pdf.php(7): edition\\Fonctions::editPDFModule()\n#6 {main}\n  thrown in /var/www/Libertempo/adico/includes/SQL.php on line 151, referer: https://adico.pa-la.fr/edition/edit_user.php

**Comment by wouldsmina** [comment]
Bonjour,
Quel version de mariadb ?
