### ISSUE TITLE
Ajout utilisateurs bloqué par l'option "gestion_conges_exceptionnels"

### ISSUE THREAD

**Issue by nemsproxi** [libertempo/web#905]
**Décrivez le bug**
Bonjour, lorsque l'on active l'option :"gestion_conges_exceptionnels", il nous est impossible d'ajouter un utilisateur depuis l'interface web. Le formulaire s'affiche bien, mais lorsque l'on valide l'ajout, la page devient blanche :

![reprod bug1](https://user-images.githubusercontent.com/58975713/82827535-879e8600-9eaf-11ea-9ff8-b53b75762c90.png)

et l'ajout n'a pas été pris en compte. Du coté d'apache2, on a cette erreur : 

![apache2_Adduser](https://user-images.githubusercontent.com/58975713/82826606-c2072380-9ead-11ea-9d51-3bfc120a8774.png)

Une fois désactivé, l'ajout d'utilisateur est a nouveau possible et refonctionne bien.

**Serveur (veuillez remplir les informations suivantes):**
 - Système: Ubuntu 18.04
 - Version de Libertempo : 1.13 Nooma 
 - Version MySQL et PHP : MariaDB 10.1.44 et PHP 7.4.6

Merci d'avance !

**Comment by cseoneohs** [comment]
I have the same problem.

**Comment by wouldsmina** [comment]
Bonjour,

L'un de vous deux pourrait il reproduire le problème sur la démo et me donner la marche à suivre ?

MErci.

**Comment by coendoup** [comment]
Bonjour,
Je constate le même bug sur une installation "neuve".

MariaDB Ver 15.1 Distrib 10.1.45-MariaDB ; php 7.3.22-1+0~20200909.67+debian9~1.gbpdd7b72.

J'ai configuré, il me semble, la même "config générale" sur la demo, mais je n'arrive pas à y reproduire le soucis.

Apache2/error.log :  
`[Sat Sep 12 23:06:08.132264 2020] [php7:warn] [pid 3416] [client ***.***.***.***:***] PHP Warning:  implode(): Invalid arguments passed in /var/www/(...)/hr/hr_ajout_user.php on line 216, referer: https://conges.***.**/hr/ajout_user
[Sat Sep 12 23:06:08.132583 2020] [php7:error] [pid 3416] [client ***.***.***.***:***] PHP Fatal error:  Uncaught mysqli_sql_exception: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '' at line 1 in /var/www/(...)/includes/SQL.php:151\nStack trace:\n#0 /var/www/(...)/includes/SQL.php(151): mysqli->real_query('INSERT INTO con...')\n#1 [internal function]: includes\\Database->query('INSERT INTO con...')\n#2 /var/www/(...)/includes/SQL.php(114): call_user_func_array(Array, Array)\n#3 /var/www/(...)/hr/hr_ajout_user.php(217): includes\\SQL->__call('query', Array)\n#4 /var/www/(...)/hr/hr_ajout_user.php(161): insertSoldeUtilisateur(Array, Object(includes\\SQL))\n#5 /var/www/(...)/hr/hr_ajout_user.php(136): insertUtilisateur(Array, Array)\n#6 /var/www/(...)/hr/hr_ajout_user.php(31): postFormUtilisateur(Array, Array, '')\n#7 /var/www/(...)/hr/hr_index.php(74): require_once('/var/www/(...)...')\n#8 /var/www/(...)/Public/index.php(67): require_once('/var/www/(...)...')\n#9 {main}\n  thrown in /var/www/(...)/includes/SQL.php on line 151, referer: https://conges.***.**/hr/ajout_user`

J'espère que cela pourra aider !

**Comment by cseoneohs** [comment]
Bonjour,
sur la démo avec l'identifiant pierre tout fonctionne correctement, impossible de reproduire le problème !

**Comment by cseoneohs** [comment]
Sinon en local dans les logs Apaches même message que coendoup...

**Comment by wouldsmina** [comment]
ok, merci. Je vais essayer en partant d'un fresh install.
