### ISSUE TITLE
Droits pour afficher la liste des groupes

### ISSUE THREAD

**Issue by nemsproxi** [libertempo/web#906]
**Décrivez le bug**

Bonjour, afin de pouvoir afficher la liste des groupes un utilisateur doit avoir les droits "HR" (pour faire afficher le menu à gauche HR qui contient le lien vers "Groupe") ET "Administrateur" (pour pouvoir voir le contenu de la page Groupe).
Si l'utilisateur n'est que Haut Responsable: il ne verra pas le contenu de la page groupe : 

![bug2-rh](https://user-images.githubusercontent.com/58975713/82879823-cf6bee80-9f3d-11ea-8807-f29c2ce37198.png)

et voici l'erreur retournée : 

[Tue May 26 08:42:09.925013 2020] [php7:error] [pid 6117] [client ###.###.###.###:63201] PHP Fatal error:  Uncaught LogicException: Erreur client : Request -> GET //api/groupe HTTP/1.1\r\nUser-Agent: GuzzleHttp/6.3.3 curl/7.58.0 PHP/7.3.17-1+ubuntu18.04.1+deb.sury.org+1\r\nHost: ####.####.local\r\nToken: $2y$10$lDdA/Dr1sJFjHO2LeqEJbuon3hpS6YRPwbh.EIsplHj03pJ8hk/hu\r\nContent-Type: application/json\r\nAccept: application/json\r\n\r\n | Response <- HTTP/1.1 403 Forbidden\r\nDate: Tue, 26 May 2020 08:42:09 GMT\r\nServer: Apache/2.4.29 (Ubuntu)\r\nContent-Length: 114\r\nContent-Type: application/json;charset=utf-8\r\n\r\n{"code":403,"status":"fail","message":"Forbidden","data":"User has not access to \\u00ab \\/groupe \\u00bb resource"} in /var/www/html/web/App/Libraries/ApiClient.php:134\nStack trace:\n#0 /var/www/html/web/App/Libraries/ApiClient.php(62): App\\Libraries\\ApiClient->request('GET', 'groupe', Array)\n#1 /var/www/html/web/App/Libraries/ApiClient.php(45): App\\Libraries\\ApiClient->securedRequest('GET', 'groupe', '$2y$10$lDdA/Dr1...')\n#2 /var/www/html/web/hr/hr_liste_groupe.php(37): App\\Libraries\\ApiClient->get('groupe', '$2y$10$lDdA/Dr1. in /var/www/html/web/App/Libraries/ApiClient.php on line 134, referer: http://#####.####.local/hr/page_principale

Si l'utilisateur a uniquement les droits Administrateurs : Il ne verra pas le menu RH : 

![bug2-Admin](https://user-images.githubusercontent.com/58975713/82879845-d4c93900-9f3d-11ea-9a84-802d0c1ede4f.png)

Est-ce que c'est un comportement normal ? 

**Serveur (veuillez remplir les informations suivantes):**
 - Système [i.e. iOS8.1] : Ubuntu 18.04
 - Version de Libertempo : 1.13 Nooma
 - Version MySQL et PHP : MariaDB 10.1.44 et PHP 7.4.6

Merci d'avance !

**Comment by wouldsmina** [comment]
Bonjour,
Non, ce n'est pas le comportement attendu.
Je vais essayer de corriger ça pour la prochaine version.
Merci.
